// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace ezored
{
namespace util
{

enum class LoggerLevel : int
{
    VERBOSE,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
};

}
} // namespace ezored

namespace std
{

template <>
struct hash<::ezored::util::LoggerLevel>
{
    size_t operator()(::ezored::util::LoggerLevel type) const
    {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
