// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

typedef NS_OPTIONS(NSUInteger, EZRLoggerLevel)
{
    EZRLoggerLevelNoLevel = 0,
    EZRLoggerLevelVerbose = 1 << 0,
    EZRLoggerLevelDebug = 1 << 1,
    EZRLoggerLevelInfo = 1 << 2,
    EZRLoggerLevelWarning = 1 << 3,
    EZRLoggerLevelError = 1 << 4,
    EZRLoggerLevelFatal = 1 << 5,
    EZRLoggerLevelAllLevels = 0 | EZRLoggerLevelVerbose | EZRLoggerLevelDebug | EZRLoggerLevelInfo | EZRLoggerLevelWarning | EZRLoggerLevelError | EZRLoggerLevelFatal,
};
