// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.helper;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class SharedDataHelper {
    public static void setCustomer(com.ezored.domain.Customer value)
    {
        CppProxy.setCustomer(value);
    }

    public static com.ezored.domain.Customer getCustomer()
    {
        return CppProxy.getCustomer();
    }

    public static void storeCustomer()
    {
        CppProxy.storeCustomer();
    }

    public static void setDemoFlag(boolean value)
    {
        CppProxy.setDemoFlag(value);
    }

    public static boolean getDemoFlag()
    {
        return CppProxy.getDemoFlag();
    }

    private static final class CppProxy extends SharedDataHelper
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        @SuppressWarnings("deprecation")
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        public static native void setCustomer(com.ezored.domain.Customer value);

        public static native com.ezored.domain.Customer getCustomer();

        public static native void storeCustomer();

        public static native void setDemoFlag(boolean value);

        public static native boolean getDemoFlag();
    }
}
