// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace ezored
{
namespace domain
{

struct InitializationData final
{
    std::string appId;
    std::string name;
    std::string basePath;
    int32_t databaseMigrationMaxVersion;
    bool debug;

    InitializationData(std::string appId_,
                       std::string name_,
                       std::string basePath_,
                       int32_t databaseMigrationMaxVersion_,
                       bool debug_)
        : appId(std::move(appId_)), name(std::move(name_)), basePath(std::move(basePath_)), databaseMigrationMaxVersion(std::move(databaseMigrationMaxVersion_)), debug(std::move(debug_))
    {
    }

    InitializationData()
        : appId(), name(), basePath(), databaseMigrationMaxVersion(), debug()
    {
    }
};

} // namespace domain
} // namespace ezored
