// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <chrono>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>

namespace ezored
{
namespace domain
{

struct Todo final
{
    int64_t id;
    std::string title;
    std::string body;
    std::unordered_map<std::string, std::string> data;
    bool done;
    std::chrono::system_clock::time_point createdAt;
    std::chrono::system_clock::time_point updatedAt;

    Todo(int64_t id_,
         std::string title_,
         std::string body_,
         std::unordered_map<std::string, std::string> data_,
         bool done_,
         std::chrono::system_clock::time_point createdAt_,
         std::chrono::system_clock::time_point updatedAt_)
        : id(std::move(id_)), title(std::move(title_)), body(std::move(body_)), data(std::move(data_)), done(std::move(done_)), createdAt(std::move(createdAt_)), updatedAt(std::move(updatedAt_))
    {
    }

    Todo()
        : id(), title(), body(), data(), done(), createdAt(), updatedAt()
    {
    }
};

} // namespace domain
} // namespace ezored
