// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace ezored
{
namespace enumerator
{

enum class CustomerStatusEnum : int
{
    ACTIVE,
    INACTIVE,
};

}
} // namespace ezored

namespace std
{

template <>
struct hash<::ezored::enumerator::CustomerStatusEnum>
{
    size_t operator()(::ezored::enumerator::CustomerStatusEnum type) const
    {
        return std::hash<int>()(static_cast<int>(type));
    }
};

} // namespace std
