// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainCustomer.h"


@implementation EZRDomainCustomer

- (nonnull instancetype)initWithId:(int64_t)id
                              name:(nonnull NSString *)name
                             token:(nonnull NSString *)token
{
    if (self = [super init]) {
        _id = id;
        _name = [name copy];
        _token = [token copy];
    }
    return self;
}

+ (nonnull instancetype)customerWithId:(int64_t)id
                                  name:(nonnull NSString *)name
                                 token:(nonnull NSString *)token
{
    return [(EZRDomainCustomer*)[self alloc] initWithId:id
                                                   name:name
                                                  token:token];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p id:%@ name:%@ token:%@>", self.class, (void *)self, @(self.id), self.name, self.token];
}

@end
