// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/ezored/domain/EZRDomainResponseError.hpp" // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated
{

EZRDomainResponseError::EZRDomainResponseError() = default;

EZRDomainResponseError::~EZRDomainResponseError() = default;

auto EZRDomainResponseError::fromCpp(JNIEnv *jniEnv, const CppType &c) -> ::djinni::LocalRef<JniType>
{
    const auto &data = ::djinni::JniClass<EZRDomainResponseError>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.field)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.message)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto EZRDomainResponseError::toCpp(JNIEnv *jniEnv, JniType j) -> CppType
{
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto &data = ::djinni::JniClass<EZRDomainResponseError>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mField)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mMessage))};
}

} // namespace djinni_generated
