// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/domain/Response.hpp"

namespace djinni_generated
{

class EZRDomainResponse final
{
public:
    using CppType = ::ezored::domain::Response;
    using JniType = jobject;

    using Boxed = EZRDomainResponse;

    ~EZRDomainResponse();

    static CppType toCpp(JNIEnv *jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c);

private:
    EZRDomainResponse();
    friend ::djinni::JniClass<EZRDomainResponse>;

    const ::djinni::GlobalRef<jclass> clazz{::djinni::jniFindClass("com/ezored/domain/Response")};
    const jmethodID jconstructor{::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZLjava/lang/String;Lcom/ezored/domain/ResponseError;Z)V")};
    const jfieldID field_mSuccess{::djinni::jniGetFieldID(clazz.get(), "mSuccess", "Z")};
    const jfieldID field_mMessage{::djinni::jniGetFieldID(clazz.get(), "mMessage", "Ljava/lang/String;")};
    const jfieldID field_mError{::djinni::jniGetFieldID(clazz.get(), "mError", "Lcom/ezored/domain/ResponseError;")};
    const jfieldID field_mHasError{::djinni::jniGetFieldID(clazz.get(), "mHasError", "Z")};
};

} // namespace djinni_generated
