// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/ezored/domain/EZRDomainResponse.hpp" // my header
#include "com/ezored/domain/EZRDomainResponseError.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated
{

EZRDomainResponse::EZRDomainResponse() = default;

EZRDomainResponse::~EZRDomainResponse() = default;

auto EZRDomainResponse::fromCpp(JNIEnv *jniEnv, const CppType &c) -> ::djinni::LocalRef<JniType>
{
    const auto &data = ::djinni::JniClass<EZRDomainResponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.success)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.message)),
                                                           ::djinni::get(::djinni_generated::EZRDomainResponseError::fromCpp(jniEnv, c.error)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.hasError)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto EZRDomainResponse::toCpp(JNIEnv *jniEnv, JniType j) -> CppType
{
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto &data = ::djinni::JniClass<EZRDomainResponse>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mSuccess)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mMessage)),
            ::djinni_generated::EZRDomainResponseError::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mError)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mHasError))};
}

} // namespace djinni_generated
