// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/net/http/HttpServer.hpp"

namespace djinni_generated
{

class EZRHttpServer final : ::djinni::JniInterface<::ezored::net::http::HttpServer, EZRHttpServer>
{
public:
    using CppType = std::shared_ptr<::ezored::net::http::HttpServer>;
    using CppOptType = std::shared_ptr<::ezored::net::http::HttpServer>;
    using JniType = jobject;

    using Boxed = EZRHttpServer;

    ~EZRHttpServer();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRHttpServer>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRHttpServer>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRHttpServer();
    friend ::djinni::JniClass<EZRHttpServer>;
    friend ::djinni::JniInterface<::ezored::net::http::HttpServer, EZRHttpServer>;
};

} // namespace djinni_generated
