// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/ezored/net/http/EZRHttpServerConfig.hpp" // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated
{

EZRHttpServerConfig::EZRHttpServerConfig() = default;

EZRHttpServerConfig::~EZRHttpServerConfig() = default;

auto EZRHttpServerConfig::fromCpp(JNIEnv *jniEnv, const CppType &c) -> ::djinni::LocalRef<JniType>
{
    const auto &data = ::djinni::JniClass<EZRHttpServerConfig>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.port)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.staticPath)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto EZRHttpServerConfig::toCpp(JNIEnv *jniEnv, JniType j) -> CppType
{
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto &data = ::djinni::JniClass<EZRHttpServerConfig>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mPort)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mStaticPath))};
}

} // namespace djinni_generated
