// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/util/Logger.hpp"

namespace djinni_generated
{

class EZRLogger final : ::djinni::JniInterface<::ezored::util::Logger, EZRLogger>
{
public:
    using CppType = std::shared_ptr<::ezored::util::Logger>;
    using CppOptType = std::shared_ptr<::ezored::util::Logger>;
    using JniType = jobject;

    using Boxed = EZRLogger;

    ~EZRLogger();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRLogger>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRLogger>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRLogger();
    friend ::djinni::JniClass<EZRLogger>;
    friend ::djinni::JniInterface<::ezored::util::Logger, EZRLogger>;
};

} // namespace djinni_generated
