// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/util/LoggerLevel.hpp"

namespace djinni_generated
{

class EZRLoggerLevel final : ::djinni::JniEnum
{
public:
    using CppType = ::ezored::util::LoggerLevel;
    using JniType = jobject;

    using Boxed = EZRLoggerLevel;

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EZRLoggerLevel>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, CppType c) { return ::djinni::JniClass<EZRLoggerLevel>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    EZRLoggerLevel() : JniEnum("com/ezored/util/LoggerLevel") {}
    friend ::djinni::JniClass<EZRLoggerLevel>;
};

} // namespace djinni_generated
