// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/systemservices/CustomerSystemService.hpp"

namespace djinni_generated {

class EZRSystemServicesCustomerSystemService final : ::djinni::JniInterface<::ezored::systemservices::CustomerSystemService, EZRSystemServicesCustomerSystemService> {
public:
    using CppType = std::shared_ptr<::ezored::systemservices::CustomerSystemService>;
    using CppOptType = std::shared_ptr<::ezored::systemservices::CustomerSystemService>;
    using JniType = jobject;

    using Boxed = EZRSystemServicesCustomerSystemService;

    ~EZRSystemServicesCustomerSystemService();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<EZRSystemServicesCustomerSystemService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<EZRSystemServicesCustomerSystemService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    EZRSystemServicesCustomerSystemService();
    friend ::djinni::JniClass<EZRSystemServicesCustomerSystemService>;
    friend ::djinni::JniInterface<::ezored::systemservices::CustomerSystemService, EZRSystemServicesCustomerSystemService>;

};

}  // namespace djinni_generated
