// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/systemservices/CustomerSystemServiceLoginData.hpp"

namespace djinni_generated {

class EZRSystemServicesCustomerSystemServiceLoginData final {
public:
    using CppType = ::ezored::systemservices::CustomerSystemServiceLoginData;
    using JniType = jobject;

    using Boxed = EZRSystemServicesCustomerSystemServiceLoginData;

    ~EZRSystemServicesCustomerSystemServiceLoginData();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    EZRSystemServicesCustomerSystemServiceLoginData();
    friend ::djinni::JniClass<EZRSystemServicesCustomerSystemServiceLoginData>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/ezored/systemservices/CustomerSystemServiceLoginData") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lcom/ezored/domain/Response;Lcom/ezored/domain/Customer;)V") };
    const jfieldID field_mResponse { ::djinni::jniGetFieldID(clazz.get(), "mResponse", "Lcom/ezored/domain/Response;") };
    const jfieldID field_mCustomer { ::djinni::jniGetFieldID(clazz.get(), "mCustomer", "Lcom/ezored/domain/Customer;") };
};

}  // namespace djinni_generated
