// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/systemservices/EZRSystemServicesCustomerSystemServiceLoginData.h"
#import <Foundation/Foundation.h>


@interface EZRSystemServicesCustomerSystemService : NSObject

+ (nonnull EZRSystemServicesCustomerSystemServiceLoginData *)login:(nonnull NSString *)username
                                                          password:(nonnull NSString *)password;

@end
