// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/systemservices/EZRSystemServiceCustomerSystemServiceLoginData.h"
#include "ezored/systemservices/CustomerSystemServiceLoginData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRSystemServiceCustomerSystemServiceLoginData;

namespace djinni_generated {

struct CustomerSystemServiceLoginData
{
    using CppType = ::ezored::systemservices::CustomerSystemServiceLoginData;
    using ObjcType = EZRSystemServiceCustomerSystemServiceLoginData*;

    using Boxed = CustomerSystemServiceLoginData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
