// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include <functional>

namespace ezored { namespace net { namespace http {

enum class HttpMethod : int {
    GET,
    POST,
    HEAD,
    PUT,
    DELETE,
    PATCH,
    CONNECT,
    OPTIONS,
    TRACE,
};

} } }  // namespace ezored::net::http

namespace std {

template <>
struct hash<::ezored::net::http::HttpMethod> {
    size_t operator()(::ezored::net::http::HttpMethod type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
