// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/helpers/EZRHelpersTodoHelper.hpp" // my header
#include "com/ezored/domain/EZRDomainTodo.hpp"

namespace djinni_generated
{

EZRHelpersTodoHelper::EZRHelpersTodoHelper() : ::djinni::JniInterface<::ezored::helpers::TodoHelper, EZRHelpersTodoHelper>("com/ezored/helpers/TodoHelper$CppProxy") {}

EZRHelpersTodoHelper::~EZRHelpersTodoHelper() = default;

CJNIEXPORT void JNICALL Java_com_ezored_helpers_TodoHelper_00024CppProxy_nativeDestroy(JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef)
{
    try
    {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ezored::helpers::TodoHelper> *>(nativeRef);
    }
    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT ::djinni_generated::EZRDomainTodo::JniType JNICALL Java_com_ezored_helpers_TodoHelper_00024CppProxy_create(JNIEnv *jniEnv, jobject /*this*/)
{
    try
    {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ezored::helpers::TodoHelper::create();
        return ::djinni::release(::djinni_generated::EZRDomainTodo::fromCpp(jniEnv, r));
    }
    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
