// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/helpers/EnvironmentHelper.hpp"

namespace djinni_generated {

class EZRHelpersEnvironmentHelper final : ::djinni::JniInterface<::ezored::helpers::EnvironmentHelper, EZRHelpersEnvironmentHelper> {
public:
    using CppType = std::shared_ptr<::ezored::helpers::EnvironmentHelper>;
    using CppOptType = std::shared_ptr<::ezored::helpers::EnvironmentHelper>;
    using JniType = jobject;

    using Boxed = EZRHelpersEnvironmentHelper;

    ~EZRHelpersEnvironmentHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<EZRHelpersEnvironmentHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<EZRHelpersEnvironmentHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    EZRHelpersEnvironmentHelper();
    friend ::djinni::JniClass<EZRHelpersEnvironmentHelper>;
    friend ::djinni::JniInterface<::ezored::helpers::EnvironmentHelper, EZRHelpersEnvironmentHelper>;

};

}  // namespace djinni_generated
