// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/helpers/SecurityHelper.hpp"

namespace djinni_generated {

class EZRHelpersSecurityHelper final : ::djinni::JniInterface<::ezored::helpers::SecurityHelper, EZRHelpersSecurityHelper> {
public:
    using CppType = std::shared_ptr<::ezored::helpers::SecurityHelper>;
    using CppOptType = std::shared_ptr<::ezored::helpers::SecurityHelper>;
    using JniType = jobject;

    using Boxed = EZRHelpersSecurityHelper;

    ~EZRHelpersSecurityHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<EZRHelpersSecurityHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<EZRHelpersSecurityHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    EZRHelpersSecurityHelper();
    friend ::djinni::JniClass<EZRHelpersSecurityHelper>;
    friend ::djinni::JniInterface<::ezored::helpers::SecurityHelper, EZRHelpersSecurityHelper>;

};

}  // namespace djinni_generated
