// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/helpers/TodoHelper.hpp"

namespace djinni_generated {

class EZRHelpersTodoHelper final : ::djinni::JniInterface<::ezored::helpers::TodoHelper, EZRHelpersTodoHelper> {
public:
    using CppType = std::shared_ptr<::ezored::helpers::TodoHelper>;
    using CppOptType = std::shared_ptr<::ezored::helpers::TodoHelper>;
    using JniType = jobject;

    using Boxed = EZRHelpersTodoHelper;

    ~EZRHelpersTodoHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<EZRHelpersTodoHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<EZRHelpersTodoHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    EZRHelpersTodoHelper();
    friend ::djinni::JniClass<EZRHelpersTodoHelper>;
    friend ::djinni::JniInterface<::ezored::helpers::TodoHelper, EZRHelpersTodoHelper>;

};

}  // namespace djinni_generated
