// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/helpers/EZRHelpersSecurityHelper.hpp"  // my header
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated {

EZRHelpersSecurityHelper::EZRHelpersSecurityHelper() : ::djinni::JniInterface<::ezored::helpers::SecurityHelper, EZRHelpersSecurityHelper>("com/ezored/helpers/SecurityHelper$CppProxy") {}

EZRHelpersSecurityHelper::~EZRHelpersSecurityHelper() = default;


CJNIEXPORT void JNICALL Java_com_ezored_helpers_SecurityHelper_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ezored::helpers::SecurityHelper>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jstring JNICALL Java_com_ezored_helpers_SecurityHelper_00024CppProxy_generateUuidV4(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ezored::helpers::SecurityHelper::generateUuidV4();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
