// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/helpers/EZRHelpersEnvironmentHelper+Private.h"
#import "ezored/helpers/EZRHelpersEnvironmentHelper.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface EZRHelpersEnvironmentHelper ()

- (id)initWithCpp:(const std::shared_ptr<::ezored::helpers::EnvironmentHelper>&)cppRef;

@end

@implementation EZRHelpersEnvironmentHelper {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ezored::helpers::EnvironmentHelper>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ezored::helpers::EnvironmentHelper>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)getSecretKey {
    try {
        auto objcpp_result_ = ::ezored::helpers::EnvironmentHelper::getSecretKey();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto EnvironmentHelper::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto EnvironmentHelper::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<EZRHelpersEnvironmentHelper>(cpp);
}

}  // namespace djinni_generated

@end
