// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "ezored/helper/EZRHelperSecurityHelper+Private.h"
#import "ezored/helper/EZRHelperSecurityHelper.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface EZRHelperSecurityHelper ()

- (id)initWithCpp:(const std::shared_ptr<::ezored::helper::SecurityHelper> &)cppRef;

@end

@implementation EZRHelperSecurityHelper
{
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ezored::helper::SecurityHelper>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ezored::helper::SecurityHelper> &)cppRef
{
    if (self = [super init])
    {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull NSString *)generateUuidV4
{
    try
    {
        auto objcpp_result_ = ::ezored::helper::SecurityHelper::generateUuidV4();
        return ::djinni::String::fromCpp(objcpp_result_);
    }
    DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated
{

auto SecurityHelper::toCpp(ObjcType objc) -> CppType
{
    if (!objc)
    {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SecurityHelper::fromCppOpt(const CppOptType &cpp) -> ObjcType
{
    if (!cpp)
    {
        return nil;
    }
    return ::djinni::get_cpp_proxy<::EZRHelperSecurityHelper>(cpp);
}

} // namespace djinni_generated

@end
