// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainCustomer.h"
#import <Foundation/Foundation.h>

@interface EZRHelperSharedDataHelper : NSObject

+ (void)setCustomer:(nonnull EZRDomainCustomer *)value;

+ (nonnull EZRDomainCustomer *)getCustomer;

+ (void)storeCustomer;

+ (void)setDemoFlag:(BOOL)value;

+ (BOOL)getDemoFlag;

@end
