// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface EZRHelperSecurityHelper : NSObject

+ (nonnull NSString *)generateUuidV4;

@end
