// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "ezored/helper/TodoHelper.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRHelperTodoHelper;

namespace djinni_generated
{

class TodoHelper
{
public:
    using CppType = std::shared_ptr<::ezored::helper::TodoHelper>;
    using CppOptType = std::shared_ptr<::ezored::helper::TodoHelper>;
    using ObjcType = ::EZRHelperTodoHelper *;

    using Boxed = TodoHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType &cpp);
    static ObjcType fromCpp(const CppType &cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated
