// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainTodo.h"
#import <Foundation/Foundation.h>

@interface EZRHelperTodoHelper : NSObject

+ (nonnull EZRDomainTodo *)create;

@end
