// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "djinni/objc/DJICppWrapperCache+Private.h"
#import "djinni/objc/DJIError.h"
#import "djinni/objc/DJIMarshal+Private.h"
#import "ezored/systemservice/EZRSystemServiceCustomerSystemService+Private.h"
#import "ezored/systemservice/EZRSystemServiceCustomerSystemService.h"
#import "ezored/systemservice/EZRSystemServiceCustomerSystemServiceLoginData+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface EZRSystemServiceCustomerSystemService ()

- (id)initWithCpp:(const std::shared_ptr<::ezored::systemservice::CustomerSystemService> &)cppRef;

@end

@implementation EZRSystemServiceCustomerSystemService
{
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::ezored::systemservice::CustomerSystemService>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::ezored::systemservice::CustomerSystemService> &)cppRef
{
    if (self = [super init])
    {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nonnull EZRSystemServiceCustomerSystemServiceLoginData *)login:(nonnull NSString *)username
                                                         password:(nonnull NSString *)password
{
    try
    {
        auto objcpp_result_ = ::ezored::systemservice::CustomerSystemService::login(::djinni::String::toCpp(username),
                                                                                    ::djinni::String::toCpp(password));
        return ::djinni_generated::CustomerSystemServiceLoginData::fromCpp(objcpp_result_);
    }
    DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated
{

auto CustomerSystemService::toCpp(ObjcType objc) -> CppType
{
    if (!objc)
    {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto CustomerSystemService::fromCppOpt(const CppOptType &cpp) -> ObjcType
{
    if (!cpp)
    {
        return nil;
    }
    return ::djinni::get_cpp_proxy<::EZRSystemServiceCustomerSystemService>(cpp);
}

} // namespace djinni_generated

@end
