// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/systemservice/EZRSystemServiceCustomerSystemServiceLoginData.h"

@implementation EZRSystemServiceCustomerSystemServiceLoginData

- (nonnull instancetype)initWithResponse:(nonnull EZRDomainResponse *)response
                                customer:(nonnull EZRDomainCustomer *)customer
{
    if (self = [super init])
    {
        _response = response;
        _customer = customer;
    }
    return self;
}

+ (nonnull instancetype)customerSystemServiceLoginDataWithResponse:(nonnull EZRDomainResponse *)response
                                                          customer:(nonnull EZRDomainCustomer *)customer
{
    return [(EZRSystemServiceCustomerSystemServiceLoginData *)[self alloc] initWithResponse:response
                                                                                   customer:customer];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p response:%@ customer:%@>", self.class, (void *)self, self.response, self.customer];
}

@end
