// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "ezored/systemservice/CustomerSystemServiceLoginData.hpp"
#import "ezored/systemservice/EZRSystemServiceCustomerSystemServiceLoginData.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRSystemServiceCustomerSystemServiceLoginData;

namespace djinni_generated
{

struct CustomerSystemServiceLoginData
{
    using CppType = ::ezored::systemservice::CustomerSystemServiceLoginData;
    using ObjcType = ::EZRSystemServiceCustomerSystemServiceLoginData *;

    using Boxed = CustomerSystemServiceLoginData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
