// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainCustomer+Private.h"
#import "ezored/domain/EZRDomainResponse+Private.h"
#import "ezored/systemservice/EZRSystemServiceCustomerSystemServiceLoginData+Private.h"
#include <cassert>

namespace djinni_generated
{

auto CustomerSystemServiceLoginData::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni_generated::Response::toCpp(obj.response),
            ::djinni_generated::Customer::toCpp(obj.customer)};
}

auto CustomerSystemServiceLoginData::fromCpp(const CppType &cpp) -> ObjcType
{
    return [[::EZRSystemServiceCustomerSystemServiceLoginData alloc] initWithResponse:(::djinni_generated::Response::fromCpp(cpp.response))
                                                                             customer:(::djinni_generated::Customer::fromCpp(cpp.customer))];
}

} // namespace djinni_generated
