// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainCustomer.h"
#import "ezored/domain/EZRDomainResponse.h"
#import <Foundation/Foundation.h>

@interface EZRSystemServiceCustomerSystemServiceLoginData : NSObject
- (nonnull instancetype)initWithResponse:(nonnull EZRDomainResponse *)response
                                customer:(nonnull EZRDomainCustomer *)customer;
+ (nonnull instancetype)customerSystemServiceLoginDataWithResponse:(nonnull EZRDomainResponse *)response
                                                          customer:(nonnull EZRDomainCustomer *)customer;

@property(nonatomic, readonly, nonnull) EZRDomainResponse *response;

@property(nonatomic, readonly, nonnull) EZRDomainCustomer *customer;

@end
