// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "ezored/domain/Todo.hpp"

namespace ezored
{
namespace helpers
{

class TodoHelper
{
public:
    virtual ~TodoHelper() {}

    static ::ezored::domain::Todo create();
};

} // namespace helpers
} // namespace ezored
