// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>


@protocol EZRSharedDataPlatformService

- (void)setString:(nonnull NSString *)key
            value:(nonnull NSString *)value;

- (void)setInteger:(nonnull NSString *)key
             value:(int32_t)value;

- (void)setLong:(nonnull NSString *)key
          value:(int64_t)value;

- (void)setBool:(nonnull NSString *)key
          value:(BOOL)value;

- (void)setFloat:(nonnull NSString *)key
           value:(float)value;

- (void)setDouble:(nonnull NSString *)key
            value:(double)value;

- (nonnull NSString *)getString:(nonnull NSString *)key;

- (int32_t)getInteger:(nonnull NSString *)key;

- (int64_t)getLong:(nonnull NSString *)key;

- (BOOL)getBool:(nonnull NSString *)key;

- (float)getFloat:(nonnull NSString *)key;

- (double)getDouble:(nonnull NSString *)key;

- (nonnull NSString *)getStringWithDefaultValue:(nonnull NSString *)key
                                   defaultValue:(nonnull NSString *)defaultValue;

- (int32_t)getIntegerWithDefaultValue:(nonnull NSString *)key
                         defaultValue:(int32_t)defaultValue;

- (int64_t)getLongWithDefaultValue:(nonnull NSString *)key
                      defaultValue:(int64_t)defaultValue;

- (BOOL)getBoolWithDefaultValue:(nonnull NSString *)key
                   defaultValue:(BOOL)defaultValue;

- (float)getFloatWithDefaultValue:(nonnull NSString *)key
                     defaultValue:(float)defaultValue;

- (double)getDoubleWithDefaultValue:(nonnull NSString *)key
                       defaultValue:(double)defaultValue;

- (BOOL)has:(nonnull NSString *)key;

- (void)remove:(nonnull NSString *)key;

- (void)clear;

- (void)save:(BOOL)async
  autoFinish:(BOOL)autoFinish;

- (void)saveAsync;

- (void)saveSync;

- (void)start:(nonnull NSString *)groupName;

- (void)finish;

@end
