// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/dataservices/TodoDataService.hpp"

namespace djinni_generated
{

class EZRDataServicesTodoDataService final : ::djinni::JniInterface<::ezored::dataservices::TodoDataService, EZRDataServicesTodoDataService>
{
public:
    using CppType = std::shared_ptr<::ezored::dataservices::TodoDataService>;
    using CppOptType = std::shared_ptr<::ezored::dataservices::TodoDataService>;
    using JniType = jobject;

    using Boxed = EZRDataServicesTodoDataService;

    ~EZRDataServicesTodoDataService();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRDataServicesTodoDataService>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRDataServicesTodoDataService>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRDataServicesTodoDataService();
    friend ::djinni::JniClass<EZRDataServicesTodoDataService>;
    friend ::djinni::JniInterface<::ezored::dataservices::TodoDataService, EZRDataServicesTodoDataService>;
};

} // namespace djinni_generated
