// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/core/ApplicationCore.hpp"

namespace djinni_generated
{

class EZRCoreApplicationCore final : ::djinni::JniInterface<::ezored::core::ApplicationCore, EZRCoreApplicationCore>
{
public:
    using CppType = std::shared_ptr<::ezored::core::ApplicationCore>;
    using CppOptType = std::shared_ptr<::ezored::core::ApplicationCore>;
    using JniType = jobject;

    using Boxed = EZRCoreApplicationCore;

    ~EZRCoreApplicationCore();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRCoreApplicationCore>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRCoreApplicationCore>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRCoreApplicationCore();
    friend ::djinni::JniClass<EZRCoreApplicationCore>;
    friend ::djinni::JniInterface<::ezored::core::ApplicationCore, EZRCoreApplicationCore>;
};

} // namespace djinni_generated
