// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "ezored/domain/Todo.hpp"
#include <cstdint>
#include <string>
#include <vector>

namespace ezored { namespace repository {

class TodoRepository {
public:
    virtual ~TodoRepository() {}

    static void truncate();

    static ::ezored::domain::Todo findById(int64_t id);

    static std::vector<::ezored::domain::Todo> findAllOrderByCreatedAtDesc();

    static std::vector<::ezored::domain::Todo> findByTitle(const std::string & title);

    static void removeById(int64_t id);

    static void update(int64_t id, const ::ezored::domain::Todo & todo);

    static int64_t insert(const ::ezored::domain::Todo & todo);

    static int64_t add(const ::ezored::domain::Todo & todo);

    static void setDoneById(int64_t id, bool done);
};

} }  // namespace ezored::repository
