// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.net.http;

public enum HttpMethod {
    GET,
    POST,
    HEAD,
    PUT,
    DELETE,
    PATCH,
    CONNECT,
    OPTIONS,
    TRACE,
    ;
}
