def run(proj_path, target_name, params):
    return {
        "project_name": "ezored",
        "version": "1.0.0",
        "build_types": ["Debug", "Release"],
        "archs": [
            {
                "arch": "armv7",
                "conan_arch": "armv7",
                "conan_profile": "ezored_ios_framework_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "armv7s",
                "conan_arch": "armv7s",
                "conan_profile": "ezored_ios_framework_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "arm64",
                "conan_arch": "armv8",
                "conan_profile": "ezored_ios_framework_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "arm64e",
                "conan_arch": "armv8.3",
                "conan_profile": "ezored_ios_framework_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_ios_framework_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneSimulator",
                "enable_bitcode": False,
                "group": "ios_simulator",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_catalyst_framework_profile",
                "min_version": "13.0",
                "supported_platform": "MacOSX",
                "enable_bitcode": False,
                "group": "ios_catalyst",
                "build_min_version": "10.15",
            },
            {
                "arch": "arm64",
                "conan_arch": "armv8",
                "conan_profile": "ezored_tvos_framework_profile",
                "min_version": "11.0",
                "supported_platform": "AppleTVOS",
                "enable_bitcode": True,
                "group": "tvos",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_tvos_framework_profile",
                "min_version": "11.0",
                "supported_platform": "AppleTVSimulator",
                "enable_bitcode": False,
                "group": "tvos_simulator",
            },
            {
                "arch": "armv7k",
                "conan_arch": "armv7k",
                "conan_profile": "ezored_watchos_framework_profile",
                "min_version": "5.0",
                "supported_platform": "WatchOS",
                "enable_bitcode": True,
                "group": "watchos",
            },
            {
                "arch": "arm64_32",
                "conan_arch": "armv8_32",
                "conan_profile": "ezored_watchos_framework_profile",
                "min_version": "5.0",
                "supported_platform": "WatchOS",
                "enable_bitcode": True,
                "group": "watchos",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_watchos_framework_profile",
                "min_version": "5.0",
                "supported_platform": "WatchSimulator",
                "enable_bitcode": False,
                "group": "watchos_simulator",
            },
        ],
        "install_headers": [
            {
                "type": "dir",
                "path": "files/gluecode/app-domain/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/app-enums/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/app-core/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/app-data-services/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/app-system-services/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/app-helpers/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/datetime/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/file-helper/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/http-client/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/shared-data/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/logger/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/gluecode/string-helper/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/src/file-helper/objc",
            },
            {
                "type": "dir",
                "path": "files/src/logger/objc",
            },
            {
                "type": "dir",
                "path": "files/src/shared-data/objc",
            },
            {
                "type": "dir",
                "path": "files/src/http-client/objc",
            },
        ],
        "umbrella_header": "Ezored.h",
    }
