def run(proj_path, target_name, params):
    return {
        "project_name": "ezored",
        "version": "1.0.0",
        "build_types": ["Debug", "Release"],
        "archs": [
            {
                "arch": "armv7",
                "conan_arch": "armv7",
                "conan_profile": "ezored_ios_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "armv7s",
                "conan_arch": "armv7s",
                "conan_profile": "ezored_ios_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "arm64",
                "conan_arch": "armv8",
                "conan_profile": "ezored_ios_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "arm64e",
                "conan_arch": "armv8.3",
                "conan_profile": "ezored_ios_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneOS",
                "enable_bitcode": True,
                "group": "ios",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_ios_profile",
                "min_version": "9.0",
                "supported_platform": "iPhoneSimulator",
                "enable_bitcode": False,
                "group": "ios_simulator",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_catalyst_profile",
                "min_version": "13.0",
                "supported_platform": "MacOSX",
                "enable_bitcode": False,
                "group": "ios_catalyst",
                "build_min_version": "10.15",
            },
            {
                "arch": "arm64",
                "conan_arch": "armv8",
                "conan_profile": "ezored_tvos_profile",
                "min_version": "11.0",
                "supported_platform": "AppleTVOS",
                "enable_bitcode": True,
                "group": "tvos",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_tvos_profile",
                "min_version": "11.0",
                "supported_platform": "AppleTVSimulator",
                "enable_bitcode": False,
                "group": "tvos_simulator",
            },
            {
                "arch": "armv7k",
                "conan_arch": "armv7k",
                "conan_profile": "ezored_watchos_profile",
                "min_version": "5.0",
                "supported_platform": "WatchOS",
                "enable_bitcode": True,
                "group": "watchos",
            },
            {
                "arch": "arm64_32",
                "conan_arch": "armv8_32",
                "conan_profile": "ezored_watchos_profile",
                "min_version": "5.0",
                "supported_platform": "WatchOS",
                "enable_bitcode": True,
                "group": "watchos",
            },
            {
                "arch": "x86_64",
                "conan_arch": "x86_64",
                "conan_profile": "ezored_watchos_profile",
                "min_version": "5.0",
                "supported_platform": "WatchSimulator",
                "enable_bitcode": False,
                "group": "watchos_simulator",
            },
        ],
        "install_headers": [
            {
                "type": "dir",
                "path": "files/modules/app-domain/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/app-enumerator/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/app-core/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/app-repository/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/app-system-service/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/app-helper/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/datetime/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/file-helper/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/http-client/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/shared-data/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/logger/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/string-helper/gluecode/generated-src/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/file-helper/implementation/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/logger/implementation/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/shared-data/implementation/objc",
            },
            {
                "type": "dir",
                "path": "files/modules/http-client/implementation/objc",
            },
        ],
        "umbrella_header": "Ezored.h",
    }
