// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/net/http/EZRHttpRequest.h"
#import "ezored/net/http/EZRHttpResponse.h"
#import <Foundation/Foundation.h>
@class EZRHttpClient;
@class EZRHttpClientLogger;
@class EZRHttpClientPlatformService;


@interface EZRHttpClient : NSObject

+ (nullable EZRHttpClient *)shared;

- (void)setPlatformService:(nullable EZRHttpClientPlatformService *)ps;

- (nullable EZRHttpClientPlatformService *)getPlatformService;

- (BOOL)hasPlatformService;

- (nonnull EZRHttpResponse *)doRequest:(nonnull EZRHttpRequest *)request;

- (void)setLogger:(nullable EZRHttpClientLogger *)logger;

- (nullable EZRHttpClientLogger *)getLogger;

- (BOOL)hasLogger;

@end
