// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, EZRLoggerLevel) { EZRLoggerLevelVerbose,
                                             EZRLoggerLevelDebug,
                                             EZRLoggerLevelInfo,
                                             EZRLoggerLevelWarning,
                                             EZRLoggerLevelError,
};
