// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/net/http/HttpMethod.hpp"

namespace djinni_generated
{

class EZRHttpMethod final : ::djinni::JniEnum
{
public:
    using CppType = ::ezored::net::http::HttpMethod;
    using JniType = jobject;

    using Boxed = EZRHttpMethod;

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EZRHttpMethod>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, CppType c) { return ::djinni::JniClass<EZRHttpMethod>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    EZRHttpMethod() : JniEnum("com/ezored/net/http/HttpMethod") {}
    friend ::djinni::JniClass<EZRHttpMethod>;
};

} // namespace djinni_generated
