// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/net/http/HttpRequestParam.hpp"

namespace djinni_generated
{

class EZRHttpRequestParam final
{
public:
    using CppType = ::ezored::net::http::HttpRequestParam;
    using JniType = jobject;

    using Boxed = EZRHttpRequestParam;

    ~EZRHttpRequestParam();

    static CppType toCpp(JNIEnv *jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c);

private:
    EZRHttpRequestParam();
    friend ::djinni::JniClass<EZRHttpRequestParam>;

    const ::djinni::GlobalRef<jclass> clazz{::djinni::jniFindClass("com/ezored/net/http/HttpRequestParam")};
    const jmethodID jconstructor{::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V")};
    const jfieldID field_mName{::djinni::jniGetFieldID(clazz.get(), "mName", "Ljava/lang/String;")};
    const jfieldID field_mValue{::djinni::jniGetFieldID(clazz.get(), "mValue", "Ljava/lang/String;")};
};

} // namespace djinni_generated
