// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/ezored/net/http/EZRHttpRequest.hpp" // my header
#include "com/ezored/net/http/EZRHttpHeader.hpp"
#include "com/ezored/net/http/EZRHttpMethod.hpp"
#include "com/ezored/net/http/EZRHttpRequestParam.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated
{

EZRHttpRequest::EZRHttpRequest() = default;

EZRHttpRequest::~EZRHttpRequest() = default;

auto EZRHttpRequest::fromCpp(JNIEnv *jniEnv, const CppType &c) -> ::djinni::LocalRef<JniType>
{
    const auto &data = ::djinni::JniClass<EZRHttpRequest>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.url)),
                                                           ::djinni::get(::djinni_generated::EZRHttpMethod::fromCpp(jniEnv, c.method)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::EZRHttpRequestParam>::fromCpp(jniEnv, c.params)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::EZRHttpHeader>::fromCpp(jniEnv, c.headers)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.body)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto EZRHttpRequest::toCpp(JNIEnv *jniEnv, JniType j) -> CppType
{
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto &data = ::djinni::JniClass<EZRHttpRequest>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mUrl)),
            ::djinni_generated::EZRHttpMethod::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mMethod)),
            ::djinni::List<::djinni_generated::EZRHttpRequestParam>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mParams)),
            ::djinni::List<::djinni_generated::EZRHttpHeader>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mHeaders)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mBody))};
}

} // namespace djinni_generated
