// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.io;

import java.util.ArrayList;

public abstract class FileHelperPlatformService {
    public abstract boolean createFile(String path);

    public abstract boolean createFileWithStringContent(String path, String content);

    public abstract boolean createFileWithBinaryContent(String path, byte[] content);

    public abstract boolean createDir(String path);

    public abstract ArrayList<String> listFiles(String path);

    public abstract String getExtension(String path);

    public abstract String getFilename(String path);

    public abstract String getBasename(String path);

    public abstract String getFilenameFromUrl(String url);

    public abstract String getBasenameFromUrl(String url);

    public abstract boolean removeFile(String path);

    public abstract boolean removeDir(String path);

    public abstract boolean isDir(String path);

    public abstract boolean isFile(String path);

    public abstract long getFileSize(String path);

    public abstract boolean copyFile(String from, String to);

    public abstract boolean moveFile(String from, String to);

    public abstract String join(String first, String second);

    public abstract String getFileContentAsString(String path);

    public abstract byte[] getFileContentAsBinary(String path);

    public abstract String getHomeDir();
}
