// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/enums/CustomerStatusEnum.hpp"

namespace djinni_generated {

class EZREnumsCustomerStatusEnum final : ::djinni::JniEnum {
public:
    using CppType = ::ezored::enums::CustomerStatusEnum;
    using JniType = jobject;

    using Boxed = EZREnumsCustomerStatusEnum;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EZREnumsCustomerStatusEnum>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<EZREnumsCustomerStatusEnum>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    EZREnumsCustomerStatusEnum() : JniEnum("com/ezored/enums/CustomerStatusEnum") {}
    friend ::djinni::JniClass<EZREnumsCustomerStatusEnum>;
};

}  // namespace djinni_generated
