// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.domain;

public final class DeviceData implements android.os.Parcelable {


    /*package*/ final String mUniqueIdentifier;

    /*package*/ final String mName;

    /*package*/ final String mSystemName;

    /*package*/ final String mSystemVersion;

    /*package*/ final String mModel;

    /*package*/ final String mLocalizedModel;

    /*package*/ final String mAppVersion;

    /*package*/ final String mAppShortVersion;

    /*package*/ final String mAppName;

    /*package*/ final float mScreenWidth;

    /*package*/ final float mScreenHeight;

    /*package*/ final float mScreenScale;

    /*package*/ final String mSystemOsName;

    /*package*/ final String mLanguage;

    /*package*/ final String mImei;

    /*package*/ final String mRegion;

    public DeviceData(
            String uniqueIdentifier,
            String name,
            String systemName,
            String systemVersion,
            String model,
            String localizedModel,
            String appVersion,
            String appShortVersion,
            String appName,
            float screenWidth,
            float screenHeight,
            float screenScale,
            String systemOsName,
            String language,
            String imei,
            String region) {
        this.mUniqueIdentifier = uniqueIdentifier;
        this.mName = name;
        this.mSystemName = systemName;
        this.mSystemVersion = systemVersion;
        this.mModel = model;
        this.mLocalizedModel = localizedModel;
        this.mAppVersion = appVersion;
        this.mAppShortVersion = appShortVersion;
        this.mAppName = appName;
        this.mScreenWidth = screenWidth;
        this.mScreenHeight = screenHeight;
        this.mScreenScale = screenScale;
        this.mSystemOsName = systemOsName;
        this.mLanguage = language;
        this.mImei = imei;
        this.mRegion = region;
    }

    public String getUniqueIdentifier() {
        return mUniqueIdentifier;
    }

    public String getName() {
        return mName;
    }

    public String getSystemName() {
        return mSystemName;
    }

    public String getSystemVersion() {
        return mSystemVersion;
    }

    public String getModel() {
        return mModel;
    }

    public String getLocalizedModel() {
        return mLocalizedModel;
    }

    public String getAppVersion() {
        return mAppVersion;
    }

    public String getAppShortVersion() {
        return mAppShortVersion;
    }

    public String getAppName() {
        return mAppName;
    }

    public float getScreenWidth() {
        return mScreenWidth;
    }

    public float getScreenHeight() {
        return mScreenHeight;
    }

    public float getScreenScale() {
        return mScreenScale;
    }

    public String getSystemOsName() {
        return mSystemOsName;
    }

    public String getLanguage() {
        return mLanguage;
    }

    public String getImei() {
        return mImei;
    }

    public String getRegion() {
        return mRegion;
    }

    @Override
    public String toString() {
        return "DeviceData{" +
                "mUniqueIdentifier=" + mUniqueIdentifier +
                "," + "mName=" + mName +
                "," + "mSystemName=" + mSystemName +
                "," + "mSystemVersion=" + mSystemVersion +
                "," + "mModel=" + mModel +
                "," + "mLocalizedModel=" + mLocalizedModel +
                "," + "mAppVersion=" + mAppVersion +
                "," + "mAppShortVersion=" + mAppShortVersion +
                "," + "mAppName=" + mAppName +
                "," + "mScreenWidth=" + mScreenWidth +
                "," + "mScreenHeight=" + mScreenHeight +
                "," + "mScreenScale=" + mScreenScale +
                "," + "mSystemOsName=" + mSystemOsName +
                "," + "mLanguage=" + mLanguage +
                "," + "mImei=" + mImei +
                "," + "mRegion=" + mRegion +
        "}";
    }


    public static final android.os.Parcelable.Creator<DeviceData> CREATOR
        = new android.os.Parcelable.Creator<DeviceData>() {
        @Override
        public DeviceData createFromParcel(android.os.Parcel in) {
            return new DeviceData(in);
        }

        @Override
        public DeviceData[] newArray(int size) {
            return new DeviceData[size];
        }
    };

    public DeviceData(android.os.Parcel in) {
        this.mUniqueIdentifier = in.readString();
        this.mName = in.readString();
        this.mSystemName = in.readString();
        this.mSystemVersion = in.readString();
        this.mModel = in.readString();
        this.mLocalizedModel = in.readString();
        this.mAppVersion = in.readString();
        this.mAppShortVersion = in.readString();
        this.mAppName = in.readString();
        this.mScreenWidth = in.readFloat();
        this.mScreenHeight = in.readFloat();
        this.mScreenScale = in.readFloat();
        this.mSystemOsName = in.readString();
        this.mLanguage = in.readString();
        this.mImei = in.readString();
        this.mRegion = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(this.mUniqueIdentifier);
        out.writeString(this.mName);
        out.writeString(this.mSystemName);
        out.writeString(this.mSystemVersion);
        out.writeString(this.mModel);
        out.writeString(this.mLocalizedModel);
        out.writeString(this.mAppVersion);
        out.writeString(this.mAppShortVersion);
        out.writeString(this.mAppName);
        out.writeFloat(this.mScreenWidth);
        out.writeFloat(this.mScreenHeight);
        out.writeFloat(this.mScreenScale);
        out.writeString(this.mSystemOsName);
        out.writeString(this.mLanguage);
        out.writeString(this.mImei);
        out.writeString(this.mRegion);
    }

}
