// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "ezored/helpers/EnvironmentHelper.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRHelpersEnvironmentHelper;

namespace djinni_generated {

class EnvironmentHelper
{
public:
    using CppType = std::shared_ptr<::ezored::helpers::EnvironmentHelper>;
    using CppOptType = std::shared_ptr<::ezored::helpers::EnvironmentHelper>;
    using ObjcType = EZRHelpersEnvironmentHelper*;

    using Boxed = EnvironmentHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

