// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/repository/TodoRepository.hpp"

namespace djinni_generated
{

class EZRRepositoryTodoRepository final : ::djinni::JniInterface<::ezored::repository::TodoRepository, EZRRepositoryTodoRepository>
{
public:
    using CppType = std::shared_ptr<::ezored::repository::TodoRepository>;
    using CppOptType = std::shared_ptr<::ezored::repository::TodoRepository>;
    using JniType = jobject;

    using Boxed = EZRRepositoryTodoRepository;

    ~EZRRepositoryTodoRepository();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRRepositoryTodoRepository>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRRepositoryTodoRepository>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRRepositoryTodoRepository();
    friend ::djinni::JniClass<EZRRepositoryTodoRepository>;
    friend ::djinni::JniInterface<::ezored::repository::TodoRepository, EZRRepositoryTodoRepository>;
};

} // namespace djinni_generated
