// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainResponse.h"
#include "ezored/domain/Response.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRDomainResponse;

namespace djinni_generated
{

struct Response
{
    using CppType = ::ezored::domain::Response;
    using ObjcType = ::EZRDomainResponse *;

    using Boxed = Response;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
