// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainResponseError.h"
#import <Foundation/Foundation.h>

@interface EZRDomainResponse : NSObject
- (nonnull instancetype)initWithSuccess:(BOOL)success
                                message:(nonnull NSString *)message
                                  error:(nonnull EZRDomainResponseError *)error
                               hasError:(BOOL)hasError;
+ (nonnull instancetype)responseWithSuccess:(BOOL)success
                                    message:(nonnull NSString *)message
                                      error:(nonnull EZRDomainResponseError *)error
                                   hasError:(BOOL)hasError;

@property(nonatomic, readonly) BOOL success;

@property(nonatomic, readonly, nonnull) NSString *message;

@property(nonatomic, readonly, nonnull) EZRDomainResponseError *error;

@property(nonatomic, readonly) BOOL hasError;

@end
