// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainResponseError.h"
#include "ezored/domain/ResponseError.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRDomainResponseError;

namespace djinni_generated
{

struct ResponseError
{
    using CppType = ::ezored::domain::ResponseError;
    using ObjcType = ::EZRDomainResponseError *;

    using Boxed = ResponseError;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
