// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "djinni/objc/DJIMarshal+Private.h"
#import "ezored/domain/EZRDomainResponse+Private.h"
#import "ezored/domain/EZRDomainResponseError+Private.h"
#include <cassert>

namespace djinni_generated
{

auto Response::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Bool::toCpp(obj.success),
            ::djinni::String::toCpp(obj.message),
            ::djinni_generated::ResponseError::toCpp(obj.error),
            ::djinni::Bool::toCpp(obj.hasError)};
}

auto Response::fromCpp(const CppType &cpp) -> ObjcType
{
    return [[::EZRDomainResponse alloc] initWithSuccess:(::djinni::Bool::fromCpp(cpp.success))
                                                message:(::djinni::String::fromCpp(cpp.message))
                                                error:(::djinni_generated::ResponseError::fromCpp(cpp.error))
                                                hasError:(::djinni::Bool::fromCpp(cpp.hasError))];
}

} // namespace djinni_generated
