// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainInitializationData.h"

@implementation EZRDomainInitializationData

- (nonnull instancetype)initWithAppId:(nonnull NSString *)appId
                                 name:(nonnull NSString *)name
                             basePath:(nonnull NSString *)basePath
          databaseMigrationMaxVersion:(int32_t)databaseMigrationMaxVersion
                                debug:(BOOL)debug
{
    if (self = [super init])
    {
        _appId = [appId copy];
        _name = [name copy];
        _basePath = [basePath copy];
        _databaseMigrationMaxVersion = databaseMigrationMaxVersion;
        _debug = debug;
    }
    return self;
}

+ (nonnull instancetype)initializationDataWithAppId:(nonnull NSString *)appId
                                               name:(nonnull NSString *)name
                                           basePath:(nonnull NSString *)basePath
                        databaseMigrationMaxVersion:(int32_t)databaseMigrationMaxVersion
                                              debug:(BOOL)debug
{
    return [(EZRDomainInitializationData *)[self alloc] initWithAppId:appId
                                                                 name:name
                                                             basePath:basePath
                                          databaseMigrationMaxVersion:databaseMigrationMaxVersion
                                                                debug:debug];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p appId:%@ name:%@ basePath:%@ databaseMigrationMaxVersion:%@ debug:%@>", self.class, (void *)self, self.appId, self.name, self.basePath, @(self.databaseMigrationMaxVersion), @(self.debug)];
}

@end
