// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainInitializationData.h"
#include "ezored/domain/InitializationData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRDomainInitializationData;

namespace djinni_generated
{

struct InitializationData
{
    using CppType = ::ezored::domain::InitializationData;
    using ObjcType = ::EZRDomainInitializationData *;

    using Boxed = InitializationData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
