// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainResponse.h"

@implementation EZRDomainResponse

- (nonnull instancetype)initWithSuccess:(BOOL)success
                                message:(nonnull NSString *)message
                                  error:(nonnull EZRDomainResponseError *)error
                               hasError:(BOOL)hasError
{
    if (self = [super init])
    {
        _success = success;
        _message = [message copy];
        _error = error;
        _hasError = hasError;
    }
    return self;
}

+ (nonnull instancetype)responseWithSuccess:(BOOL)success
                                    message:(nonnull NSString *)message
                                      error:(nonnull EZRDomainResponseError *)error
                                   hasError:(BOOL)hasError
{
    return [(EZRDomainResponse *)[self alloc] initWithSuccess:success
                                                      message:message
                                                        error:error
                                                     hasError:hasError];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p success:%@ message:%@ error:%@ hasError:%@>", self.class, (void *)self, @(self.success), self.message, self.error, @(self.hasError)];
}

@end
