// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "ezored/domain/Customer.hpp"
#import "ezored/domain/EZRDomainCustomer.h"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRDomainCustomer;

namespace djinni_generated
{

struct Customer
{
    using CppType = ::ezored::domain::Customer;
    using ObjcType = ::EZRDomainCustomer *;

    using Boxed = Customer;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
