// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.domain;

public final class Customer implements android.os.Parcelable {


    /*package*/ final long mId;

    /*package*/ final String mName;

    /*package*/ final String mToken;

    public Customer(
            long id,
            String name,
            String token) {
        this.mId = id;
        this.mName = name;
        this.mToken = token;
    }

    public long getId() {
        return mId;
    }

    public String getName() {
        return mName;
    }

    public String getToken() {
        return mToken;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "mId=" + mId +
                "," + "mName=" + mName +
                "," + "mToken=" + mToken +
        "}";
    }


    public static final android.os.Parcelable.Creator<Customer> CREATOR
        = new android.os.Parcelable.Creator<Customer>() {
        @Override
        public Customer createFromParcel(android.os.Parcel in) {
            return new Customer(in);
        }

        @Override
        public Customer[] newArray(int size) {
            return new Customer[size];
        }
    };

    public Customer(android.os.Parcel in) {
        this.mId = in.readLong();
        this.mName = in.readString();
        this.mToken = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeLong(this.mId);
        out.writeString(this.mName);
        out.writeString(this.mToken);
    }

}
