// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/helper/StringHelper.hpp"

namespace djinni_generated
{

class EZRStringHelper final : ::djinni::JniInterface<::ezored::helper::StringHelper, EZRStringHelper>
{
public:
    using CppType = std::shared_ptr<::ezored::helper::StringHelper>;
    using CppOptType = std::shared_ptr<::ezored::helper::StringHelper>;
    using JniType = jobject;

    using Boxed = EZRStringHelper;

    ~EZRStringHelper();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRStringHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRStringHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRStringHelper();
    friend ::djinni::JniClass<EZRStringHelper>;
    friend ::djinni::JniInterface<::ezored::helper::StringHelper, EZRStringHelper>;
};

} // namespace djinni_generated
