// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "ezored/domain/Customer.hpp"
#include <string>

namespace ezored
{
namespace helper
{

class CustomerHelper
{
public:
    virtual ~CustomerHelper() {}

    static bool isLogged();

    static std::string getToken();

    static ::ezored::domain::Customer create();

    static void onCustomerLogin(const ::ezored::domain::Customer &customer);
};

} // namespace helper
} // namespace ezored
