// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>

namespace ezored
{
namespace helper
{

class EnvironmentHelper
{
public:
    virtual ~EnvironmentHelper() {}

    static std::string getSecretKey();
};

} // namespace helper
} // namespace ezored
