// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include <string>

namespace ezored
{
namespace helper
{

class SecurityHelper
{
public:
    virtual ~SecurityHelper() {}

    static std::string generateUuidV4();
};

} // namespace helper
} // namespace ezored
