// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "ezored/domain/Todo.hpp"

namespace ezored
{
namespace helper
{

class TodoHelper
{
public:
    virtual ~TodoHelper() {}

    static ::ezored::domain::Todo create();
};

} // namespace helper
} // namespace ezored
