// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/helpers/CustomerHelper.hpp"

namespace djinni_generated {

class EZRHelpersCustomerHelper final : ::djinni::JniInterface<::ezored::helpers::CustomerHelper, EZRHelpersCustomerHelper> {
public:
    using CppType = std::shared_ptr<::ezored::helpers::CustomerHelper>;
    using CppOptType = std::shared_ptr<::ezored::helpers::CustomerHelper>;
    using JniType = jobject;

    using Boxed = EZRHelpersCustomerHelper;

    ~EZRHelpersCustomerHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<EZRHelpersCustomerHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<EZRHelpersCustomerHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    EZRHelpersCustomerHelper();
    friend ::djinni::JniClass<EZRHelpersCustomerHelper>;
    friend ::djinni::JniInterface<::ezored::helpers::CustomerHelper, EZRHelpersCustomerHelper>;

};

}  // namespace djinni_generated
