// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/helpers/EnvironmentHelper.hpp"

namespace djinni_generated {

class EZRHelperEnvironmentHelper final : ::djinni::JniInterface<::ezored::helpers::EnvironmentHelper, EZRHelperEnvironmentHelper> {
public:
    using CppType = std::shared_ptr<::ezored::helpers::EnvironmentHelper>;
    using CppOptType = std::shared_ptr<::ezored::helpers::EnvironmentHelper>;
    using JniType = jobject;

    using Boxed = EZRHelperEnvironmentHelper;

    ~EZRHelperEnvironmentHelper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<EZRHelperEnvironmentHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<EZRHelperEnvironmentHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    EZRHelperEnvironmentHelper();
    friend ::djinni::JniClass<EZRHelperEnvironmentHelper>;
    friend ::djinni::JniInterface<::ezored::helpers::EnvironmentHelper, EZRHelperEnvironmentHelper>;

};

}  // namespace djinni_generated
