// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/enumerator/CustomerStatusEnum.hpp"

namespace djinni_generated
{

class EZREnumeratorCustomerStatusEnum final : ::djinni::JniEnum
{
public:
    using CppType = ::ezored::enumerator::CustomerStatusEnum;
    using JniType = jobject;

    using Boxed = EZREnumeratorCustomerStatusEnum;

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EZREnumeratorCustomerStatusEnum>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, CppType c) { return ::djinni::JniClass<EZREnumeratorCustomerStatusEnum>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    EZREnumeratorCustomerStatusEnum() : JniEnum("com/ezored/enumerator/CustomerStatusEnum") {}
    friend ::djinni::JniClass<EZREnumeratorCustomerStatusEnum>;
};

} // namespace djinni_generated
