// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, EZRHttpMethod)
{
    EZRHttpMethodGet,
    EZRHttpMethodPost,
    EZRHttpMethodHead,
    EZRHttpMethodPut,
    EZRHttpMethodDelete,
    EZRHttpMethodPatch,
    EZRHttpMethodConnect,
    EZRHttpMethodOptions,
    EZRHttpMethodTrace,
};
