// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/domain/EZRDomainCustomer+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Customer::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.id),
            ::djinni::String::toCpp(obj.name),
            ::djinni::String::toCpp(obj.token)};
}

auto Customer::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[EZRDomainCustomer alloc] initWithId:(::djinni::I64::fromCpp(cpp.id))
                                            name:(::djinni::String::fromCpp(cpp.name))
                                           token:(::djinni::String::fromCpp(cpp.token))];
}

}  // namespace djinni_generated
