"""Constants"""

DIR_NAME_FILES = 'files'
DIR_NAME_DJINNI = 'djinni'
DIR_NAME_HOME_CONAN = '.conan'
DIR_NAME_HOME_CONAN_PROFILES = 'profiles'
DIR_NAME_BUILD = 'build'
DIR_NAME_BUILD_TARGETS = 'targets'
DIR_NAME_BUILD_TARGET = 'target'
DIR_NAME_DIST = 'dist'
DIR_NAME_BUILD_CONAN = 'conan'
DIR_NAME_FILES_CMAKE = 'cmake'
DIR_NAME_FILES_TARGETS = 'targets'
DIR_NAME_FILES_TARGET_CMAKE = 'cmake'
DIR_NAME_FILES_TARGET_CONAN = 'conan'
DIR_NAME_FILES_TARGET_CONAN_PROFILE = 'profile'
DIR_NAME_FILES_TARGET_CONAN_RECIPE = 'recipe'
DIR_NAME_FILES_TARGET_VERBS = 'verbs'
DIR_NAME_FILES_TARGET_CONFIG = 'config'
DIR_NAME_FILES_TARGET_SUPPORT = 'support'
DIR_NAME_FILES_COMMANDS = 'commands'
DIR_NAME_FILES_SRC = 'src'
DIR_NAME_PROJECTS = 'projects'

FILE_NAME_FILES_TARGET_CONFIG = 'config.py'
FILE_NAME_FILES_TARGET_CONAN_RECIPE_CONANFILE_TXT = 'conanfile.txt'
FILE_NAME_FILES_TARGET_CONAN_RECIPE_CONANFILE_PY = 'conanfile.py'

COMMAND_NAME_CONFIG = 'config'

TARGET_VERBS_INTERNAL = [
    'config'
]
