// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.net.http;

public final class HttpRequestParam implements android.os.Parcelable {


    /*package*/ final String mName;

    /*package*/ final String mValue;

    public HttpRequestParam(
            String name,
            String value) {
        this.mName = name;
        this.mValue = value;
    }

    public String getName() {
        return mName;
    }

    public String getValue() {
        return mValue;
    }

    @Override
    public String toString() {
        return "HttpRequestParam{" +
                "mName=" + mName +
                "," + "mValue=" + mValue +
        "}";
    }


    public static final android.os.Parcelable.Creator<HttpRequestParam> CREATOR
        = new android.os.Parcelable.Creator<HttpRequestParam>() {
        @Override
        public HttpRequestParam createFromParcel(android.os.Parcel in) {
            return new HttpRequestParam(in);
        }

        @Override
        public HttpRequestParam[] newArray(int size) {
            return new HttpRequestParam[size];
        }
    };

    public HttpRequestParam(android.os.Parcel in) {
        this.mName = in.readString();
        this.mValue = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(this.mName);
        out.writeString(this.mValue);
    }

}
