// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.net.http;

public enum HttpMethod {
    METHOD_GET,
    METHOD_POST,
    METHOD_HEAD,
    METHOD_PUT,
    METHOD_DELETE,
    METHOD_PATCH,
    METHOD_CONNECT,
    METHOD_OPTIONS,
    METHOD_TRACE,
    ;
}
