// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface EZRStringHelper : NSObject

+ (nonnull NSString *)trim:(nonnull NSString *)value;

+ (nonnull NSString *)leftTrim:(nonnull NSString *)value;

+ (nonnull NSString *)rightTrim:(nonnull NSString *)value;

+ (nonnull NSString *)toLower:(nonnull NSString *)value;

+ (nonnull NSString *)toUpper:(nonnull NSString *)value;

+ (nonnull NSArray<NSString *> *)split:(nonnull NSString *)text
                                   sep:(nonnull NSString *)sep
                             trimEmpty:(BOOL)trimEmpty;

@end
