// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.util;

public enum LoggerLevel {
    VERBOSE,
    DEBUG,
    INFO,
    WARNING,
    ERROR,
    ;
}
