// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.net.http;

public final class HttpRequestParam {


    /*package*/ final String mName;

    /*package*/ final String mValue;

    public HttpRequestParam(
            String name,
            String value) {
        this.mName = name;
        this.mValue = value;
    }

    public String getName() {
        return mName;
    }

    public String getValue() {
        return mValue;
    }

    @Override
    public String toString() {
        return "HttpRequestParam{" +
                "mName=" + mName +
                "," + "mValue=" + mValue +
        "}";
    }

}
