// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.net.http;

public abstract class HttpClientPlatformService {
    public abstract HttpResponse doRequest(HttpRequest request);
}
