// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.util;

public abstract class LoggerPlatformService {
    public abstract void v(String message);

    public abstract void d(String message);

    public abstract void i(String message);

    public abstract void w(String message);

    public abstract void e(String message);

    public abstract void setGroup(String group);
}
