// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "ezored/enums/CustomerStatusEnum.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace ezored { namespace domain {

struct Customer final {
    int64_t id;
    std::string name;
    std::string token;
    ::ezored::enums::CustomerStatusEnum status;

    Customer(int64_t id_,
             std::string name_,
             std::string token_,
             ::ezored::enums::CustomerStatusEnum status_)
    : id(std::move(id_))
    , name(std::move(name_))
    , token(std::move(token_))
    , status(std::move(status_))
    {}
};

} }  // namespace ezored::domain
