// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.systemservice;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class CustomerSystemService {
    public static CustomerSystemServiceLoginData login(String username, String password)
    {
        return CppProxy.login(username,
                              password);
    }

    private static final class CppProxy extends CustomerSystemService
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        @SuppressWarnings("deprecation")
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        public static native CustomerSystemServiceLoginData login(String username, String password);
    }
}
