// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

package com.ezored.systemservice;

public final class CustomerSystemServiceLoginData {


    /*package*/ final com.ezored.domain.Response mResponse;

    /*package*/ final com.ezored.domain.Customer mCustomer;

    public CustomerSystemServiceLoginData(
            com.ezored.domain.Response response,
            com.ezored.domain.Customer customer) {
        this.mResponse = response;
        this.mCustomer = customer;
    }

    public com.ezored.domain.Response getResponse() {
        return mResponse;
    }

    public com.ezored.domain.Customer getCustomer() {
        return mCustomer;
    }

    @Override
    public String toString() {
        return "CustomerSystemServiceLoginData{" +
                "mResponse=" + mResponse +
                "," + "mCustomer=" + mCustomer +
        "}";
    }

}
