// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "com/ezored/systemservice/EZRSystemServiceCustomerSystemService.hpp" // my header
#include "com/ezored/systemservice/EZRSystemServiceCustomerSystemServiceLoginData.hpp"
#include "djinni/jni/Marshal.hpp"

namespace djinni_generated
{

EZRSystemServiceCustomerSystemService::EZRSystemServiceCustomerSystemService() : ::djinni::JniInterface<::ezored::systemservice::CustomerSystemService, EZRSystemServiceCustomerSystemService>("com/ezored/systemservice/CustomerSystemService$CppProxy") {}

EZRSystemServiceCustomerSystemService::~EZRSystemServiceCustomerSystemService() = default;

CJNIEXPORT void JNICALL Java_com_ezored_systemservice_CustomerSystemService_00024CppProxy_nativeDestroy(JNIEnv *jniEnv, jobject /*this*/, jlong nativeRef)
{
    try
    {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::ezored::systemservice::CustomerSystemService> *>(nativeRef);
    }
    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_ezored_systemservice_CustomerSystemService_00024CppProxy_login(JNIEnv *jniEnv, jobject /*this*/, jstring j_username, jstring j_password)
{
    try
    {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::ezored::systemservice::CustomerSystemService::login(::djinni::String::toCpp(jniEnv, j_username),
                                                                       ::djinni::String::toCpp(jniEnv, j_password));
        return ::djinni::release(::djinni_generated::EZRSystemServiceCustomerSystemServiceLoginData::fromCpp(jniEnv, r));
    }
    JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

} // namespace djinni_generated
