// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

@interface EZRDomainResponseError : NSObject
- (nonnull instancetype)initWithField:(nonnull NSString *)field
                              message:(nonnull NSString *)message;
+ (nonnull instancetype)responseErrorWithField:(nonnull NSString *)field
                                       message:(nonnull NSString *)message;

@property (nonatomic, readonly, nonnull) NSString * field;

@property (nonatomic, readonly, nonnull) NSString * message;

@end
