// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "djinni/objc/DJIMarshal+Private.h"
#import "ezored/net/http/EZRHttpRequestParam+Private.h"
#include <cassert>

namespace djinni_generated
{

auto HttpRequestParam::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.name),
            ::djinni::String::toCpp(obj.value)};
}

auto HttpRequestParam::fromCpp(const CppType &cpp) -> ObjcType
{
    return [[::EZRHttpRequestParam alloc] initWithName:(::djinni::String::fromCpp(cpp.name))
                                                 value:(::djinni::String::fromCpp(cpp.value))];
}

} // namespace djinni_generated
