// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/net/http/EZRHttpRequestParam.h"
#include "ezored/net/http/HttpRequestParam.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRHttpRequestParam;

namespace djinni_generated
{

struct HttpRequestParam
{
    using CppType = ::ezored::net::http::HttpRequestParam;
    using ObjcType = ::EZRHttpRequestParam *;

    using Boxed = HttpRequestParam;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
