// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/net/http/EZRHttpRequest.h"
#import "ezored/net/http/EZRHttpResponse.h"
#import <Foundation/Foundation.h>

@interface EZRHttpClientLogger : NSObject

- (void)onRequest:(nonnull EZRHttpRequest *)request;

- (void)onResponse:(nonnull EZRHttpRequest *)request
          response:(nonnull EZRHttpResponse *)response;

@end
