// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/net/http/EZRHttpHeader.h"
#import "ezored/net/http/EZRHttpMethod.h"
#import "ezored/net/http/EZRHttpRequestParam.h"
#import <Foundation/Foundation.h>

@interface EZRHttpRequest : NSObject
- (nonnull instancetype)initWithUrl:(nonnull NSString *)url
                             method:(EZRHttpMethod)method
                             params:(nonnull NSArray<EZRHttpRequestParam *> *)params
                            headers:(nonnull NSArray<EZRHttpHeader *> *)headers
                               body:(nonnull NSString *)body;
+ (nonnull instancetype)httpRequestWithUrl:(nonnull NSString *)url
                                    method:(EZRHttpMethod)method
                                    params:(nonnull NSArray<EZRHttpRequestParam *> *)params
                                   headers:(nonnull NSArray<EZRHttpHeader *> *)headers
                                      body:(nonnull NSString *)body;

@property(nonatomic, readonly, nonnull) NSString *url;

@property(nonatomic, readonly) EZRHttpMethod method;

@property(nonatomic, readonly, nonnull) NSArray<EZRHttpRequestParam *> *params;

@property(nonatomic, readonly, nonnull) NSArray<EZRHttpHeader *> *headers;

@property(nonatomic, readonly, nonnull) NSString *body;

@end
