// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "ezored/net/http/HttpClientPlatformService.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol EZRHttpClientPlatformService;

namespace djinni_generated
{

class HttpClientPlatformService
{
public:
    using CppType = std::shared_ptr<::ezored::net::http::HttpClientPlatformService>;
    using CppOptType = std::shared_ptr<::ezored::net::http::HttpClientPlatformService>;
    using ObjcType = id<EZRHttpClientPlatformService>;

    using Boxed = HttpClientPlatformService;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType &cpp);
    static ObjcType fromCpp(const CppType &cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated
