// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "djinni/objc/DJIMarshal+Private.h"
#import "ezored/net/http/EZRHttpHeader+Private.h"
#import "ezored/net/http/EZRHttpMethod+Private.h"
#import "ezored/net/http/EZRHttpRequest+Private.h"
#import "ezored/net/http/EZRHttpRequestParam+Private.h"
#include <cassert>

namespace djinni_generated
{

auto HttpRequest::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.url),
            ::djinni::Enum<::ezored::net::http::HttpMethod, EZRHttpMethod>::toCpp(obj.method),
            ::djinni::List<::djinni_generated::HttpRequestParam>::toCpp(obj.params),
            ::djinni::List<::djinni_generated::HttpHeader>::toCpp(obj.headers),
            ::djinni::String::toCpp(obj.body)};
}

auto HttpRequest::fromCpp(const CppType &cpp) -> ObjcType
{
    return [[::EZRHttpRequest alloc] initWithUrl:(::djinni::String::fromCpp(cpp.url))
                                          method:(::djinni::Enum<::ezored::net::http::HttpMethod, EZRHttpMethod>::fromCpp(cpp.method))
                                          params:(::djinni::List<::djinni_generated::HttpRequestParam>::fromCpp(cpp.params))
                                          headers:(::djinni::List<::djinni_generated::HttpHeader>::fromCpp(cpp.headers))
                                          body:(::djinni::String::fromCpp(cpp.body))];
}

} // namespace djinni_generated
