// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, EZRHttpMethod) { EZRHttpMethodMethodGet,
                                            EZRHttpMethodMethodPost,
                                            EZRHttpMethodMethodHead,
                                            EZRHttpMethodMethodPut,
                                            EZRHttpMethodMethodDelete,
                                            EZRHttpMethodMethodPatch,
                                            EZRHttpMethodMethodConnect,
                                            EZRHttpMethodMethodOptions,
                                            EZRHttpMethodMethodTrace,
};
