// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/net/http/EZRHttpResponse.h"
#include "ezored/net/http/HttpResponse.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRHttpResponse;

namespace djinni_generated
{

struct HttpResponse
{
    using CppType = ::ezored::net::http::HttpResponse;
    using ObjcType = ::EZRHttpResponse *;

    using Boxed = HttpResponse;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
