// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#import "ezored/net/http/EZRHttpHeader.h"
#include "ezored/net/http/HttpHeader.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class EZRHttpHeader;

namespace djinni_generated
{

struct HttpHeader
{
    using CppType = ::ezored::net::http::HttpHeader;
    using ObjcType = ::EZRHttpHeader *;

    using Boxed = HttpHeader;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType &cpp);
};

} // namespace djinni_generated
