// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import "ezored/systemservices/EZRSystemServiceCustomerSystemServiceLoginData.h"
#import <Foundation/Foundation.h>


@interface EZRSystemServiceCustomerSystemService : NSObject

+ (nonnull EZRSystemServiceCustomerSystemServiceLoginData *)login:(nonnull NSString *)username
                                                         password:(nonnull NSString *)password;

@end
