// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#pragma once

#include "djinni_support.hpp"
#include "ezored/util/LoggerLevel.hpp"

namespace djinni_generated {

class EZRLoggerLevel final : ::djinni::JniFlags {
public:
    using CppType = ::ezored::util::LoggerLevel;
    using JniType = jobject;

    using Boxed = EZRLoggerLevel;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<EZRLoggerLevel>::get().flags(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<EZRLoggerLevel>::get().create(jniEnv, static_cast<unsigned>(c), 6); }

private:
    EZRLoggerLevel() : JniFlags("com/ezored/util/LoggerLevel") {}
    friend ::djinni::JniClass<EZRLoggerLevel>;
};

}  // namespace djinni_generated
