// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#pragma once

#include "djinni/jni/djinni_support.hpp"
#include "ezored/io/FileHelper.hpp"

namespace djinni_generated
{

class EZRFileHelper final : ::djinni::JniInterface<::ezored::io::FileHelper, EZRFileHelper>
{
public:
    using CppType = std::shared_ptr<::ezored::io::FileHelper>;
    using CppOptType = std::shared_ptr<::ezored::io::FileHelper>;
    using JniType = jobject;

    using Boxed = EZRFileHelper;

    ~EZRFileHelper();

    static CppType toCpp(JNIEnv *jniEnv, JniType j) { return ::djinni::JniClass<EZRFileHelper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv *jniEnv, const CppOptType &c) { return {jniEnv, ::djinni::JniClass<EZRFileHelper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv *jniEnv, const CppType &c) { return fromCppOpt(jniEnv, c); }

private:
    EZRFileHelper();
    friend ::djinni::JniClass<EZRFileHelper>;
    friend ::djinni::JniInterface<::ezored::io::FileHelper, EZRFileHelper>;
};

} // namespace djinni_generated
