// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#import <Foundation/Foundation.h>


@interface EZRHelpersEnvironmentHelper : NSObject

+ (nonnull NSString *)getSecretKey;

@end
