// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from proj.djinni

#include "ezored/io/FileHelperPlatformService.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol EZRFileHelperPlatformService;

namespace djinni_generated
{

class FileHelperPlatformService
{
public:
    using CppType = std::shared_ptr<::ezored::io::FileHelperPlatformService>;
    using CppOptType = std::shared_ptr<::ezored::io::FileHelperPlatformService>;
    using ObjcType = id<EZRFileHelperPlatformService>;

    using Boxed = FileHelperPlatformService;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType &cpp);
    static ObjcType fromCpp(const CppType &cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

} // namespace djinni_generated
