"""Constants"""

DIR_NAME_EZORED = "ezored"
DIR_NAME_EZORED_CMD = "cmd"
DIR_NAME_FILES = "files"
DIR_NAME_GLUECODE = "gluecode"
DIR_NAME_HOME_CONAN = ".conan"
DIR_NAME_HOME_CONAN_PROFILES = "profiles"
DIR_NAME_BUILD = "build"
DIR_NAME_BUILD_TARGETS = "targets"
DIR_NAME_BUILD_TARGET = "target"
DIR_NAME_DIST = "dist"
DIR_NAME_BUILD_CONAN = "conan"
DIR_NAME_FILES_CMAKE = "cmake"
DIR_NAME_FILES_COMMANDS = "commands"
DIR_NAME_FILES_CONFIG = "config"
DIR_NAME_FILES_DOCS = "docs"
DIR_NAME_FILES_MODULES = "modules"
DIR_NAME_FILES_COMMON = "common"
DIR_NAME_FILES_TARGETS = "targets"
DIR_NAME_FILES_TARGET_CMAKE = "cmake"
DIR_NAME_FILES_TARGET_CONAN = "conan"
DIR_NAME_FILES_TARGET_CONAN_PROFILE = "profile"
DIR_NAME_FILES_TARGET_CONAN_RECIPE = "recipe"
DIR_NAME_FILES_TARGET_VERBS = "verbs"
DIR_NAME_FILES_TARGET_SUPPORT = "support"
DIR_NAME_SUPPORT = "support"
DIR_NAME_PROJECTS = "projects"
DIR_NAME_BUILD_DOCS = "docs"

FILE_NAME_FILES_TARGET_CONAN_RECIPE_CONANFILE_TXT = "conanfile.txt"
FILE_NAME_FILES_TARGET_CONAN_RECIPE_CONANFILE_PY = "conanfile.py"
FILE_NAME_DIST_PACKED = "dist.tar.gz"

GLUECODE_TOOL_VERSION = "1.2.0"

AWS_KEY_ID_ENV = "EZORED_AWS_KEY_ID"
AWS_SECRET_KEY_ENV = "EZORED_AWS_SECRET_KEY"

AWS_S3_BUCKET_NAME = "ezored"
AWS_S3_DOCS_BUCKET_NAME = "ezored"
AWS_S3_BUCKET_PATH = "dist"
AWS_S3_URL = "https://{0}.s3.amazonaws.com/{1}".format(
    AWS_S3_BUCKET_NAME, AWS_S3_BUCKET_PATH
)

TARGET_VERBS_INTERNAL = ["config"]

PROFILE_BUILD_WINDOWS = "default"
PROFILE_BUILD_MACOS = "default"
PROFILE_BUILD_LINUX = "default"
PROFILE_BUILD_DEFAULT = "default"

DOCS_DEFAULT_NAME = "default"
