// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

#include "com/ezored/net/http/EZRHttpClientPlatformService.hpp"  // my header
#include "com/ezored/net/http/EZRHttpRequest.hpp"
#include "com/ezored/net/http/EZRHttpResponse.hpp"

namespace djinni_generated {

EZRHttpClientPlatformService::EZRHttpClientPlatformService() : ::djinni::JniInterface<::ezored::net::http::HttpClientPlatformService, EZRHttpClientPlatformService>() {}

EZRHttpClientPlatformService::~EZRHttpClientPlatformService() = default;

EZRHttpClientPlatformService::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

EZRHttpClientPlatformService::JavaProxy::~JavaProxy() = default;

::ezored::net::http::HttpResponse EZRHttpClientPlatformService::JavaProxy::doRequest(const ::ezored::net::http::HttpRequest & c_request) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::EZRHttpClientPlatformService>::get();
    auto jret = jniEnv->CallObjectMethod(Handle::get().get(), data.method_doRequest,
                                         ::djinni::get(::djinni_generated::EZRHttpRequest::fromCpp(jniEnv, c_request)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni_generated::EZRHttpResponse::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
